Repository owncloud/search_elastic, pull requests merged in 2020-12, with the labels that each got.

#189 [tests-only] Implement SonarCloud analysis in CI
  .drone.star
  .gitignore
  sonar-project.properties
Labels: QA-Team

#192 [tests-only] Add starlark code to handle the case when a repo has no code coverage tests
  .drone.star
Labels: 4 - To release, QA-Team

#193 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-Team

#195 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To review, QA-Team
